services:
  pm-manager:
    build: .
    container_name: pm-manager
    restart: on-failure:3
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_REPO=${GITHUB_REPO}
    volumes:
      - ./data:/app/data
      - ./schedule.yaml:/app/schedule.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
